// Package api_gateway Code generated by swaggo/swag. DO NOT EDIT
package api_gateway

import "github.com/swaggo/swag"

const docTemplateopenapi_api_gateway = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gpus": {
            "get": {
                "description": "Returns a list of all GPUs for which telemetry data is available, served from an in-memory cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpus"
                ],
                "summary": "List all GPUs",
                "responses": {
                    "200": {
                        "description": "List of GPU summaries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.GPUSummary"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway timeout",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/gpus/{id}/telemetry": {
            "get": {
                "description": "Returns telemetry entries for a specific GPU ordered by timestamp. Supports optional RFC3339 time window filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpus"
                ],
                "summary": "Get GPU telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU hardware UUID (e.g. GPU-5fd4f087-86f3-7a43-b711-4771313afc50)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start of the time window, RFC3339 format, inclusive. Default: 1 hour ago.",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End of the time window, RFC3339 format, inclusive. Default: now.",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Telemetry response with id, count, and data array",
                        "schema": {
                            "$ref": "#/definitions/server.TelemetryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request – invalid time format or start \u003e end",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "GPU not found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway timeout",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 while the api-gateway process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns a JSON snapshot of gateway counters: requests total, success, error, cache hits/misses, and DB query errors.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Gateway metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.Snapshot"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 when the database connection is established. Returns 503 during startup or when the DB is unavailable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.Snapshot": {
            "type": "object",
            "properties": {
                "db_query_errors_total": {
                    "type": "integer"
                },
                "gpu_list_cache_hits_total": {
                    "type": "integer"
                },
                "gpu_list_cache_misses_total": {
                    "type": "integer"
                },
                "requests_error_total": {
                    "type": "integer"
                },
                "requests_success_total": {
                    "type": "integer"
                },
                "requests_total": {
                    "type": "integer"
                },
                "uptime_seconds": {
                    "type": "integer"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.ReadyResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "server.TelemetryResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "data": {},
                "id": {
                    "type": "string",
                    "example": "GPU-5fd4..."
                }
            }
        },
        "store.GPUSummary": {
            "type": "object",
            "properties": {
                "gpu_id": {
                    "description": "GpuID is the ordinal index on that host (e.g. \"0\", \"1\").",
                    "type": "string"
                },
                "hostname": {
                    "description": "Hostname is the originating node (e.g. \"mtv5-dgx1-hgpu-031\").",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the hardware UUID (e.g. \"GPU-5fd4f087-86f3-7a43-b711-4771313afc50\").\nIt is the value that callers must supply to GET /gpus/{id}/telemetry.",
                    "type": "string"
                },
                "model_name": {
                    "description": "ModelName is the GPU product name (e.g. \"NVIDIA H100 80GB HBM3\").",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoopenapi_api_gateway holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi_api_gateway = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GPU Telemetry Pipeline — API Gateway",
	Description:      "REST API for querying GPU telemetry data collected from an AI cluster.",
	InfoInstanceName: "openapi_api_gateway",
	SwaggerTemplate:  docTemplateopenapi_api_gateway,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi_api_gateway.InstanceName(), SwaggerInfoopenapi_api_gateway)
}
