// Package streamer Code generated by swaggo/swag. DO NOT EDIT
package streamer

import "github.com/swaggo/swag"

const docTemplateopenapi_streamer = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns 200 while the streamer process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns a JSON snapshot of streamer counters: rows sent, errors, last sent timestamp, and last row-read timestamp.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Streamer metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.Snapshot"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 when the telemetry loop is actively running. Returns 503 during startup and graceful shutdown.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.Snapshot": {
            "type": "object",
            "properties": {
                "errors_total": {
                    "type": "integer"
                },
                "last_row_read_timestamp_seconds": {
                    "type": "number"
                },
                "last_sent_timestamp_seconds": {
                    "type": "number"
                },
                "rows_sent_total": {
                    "type": "integer"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.ReadyResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        }
    }
}`

// SwaggerInfoopenapi_streamer holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi_streamer = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GPU Telemetry Pipeline — Streamer API",
	Description:      "Internal health and observability API for the Telemetry Streamer service.",
	InfoInstanceName: "openapi_streamer",
	SwaggerTemplate:  docTemplateopenapi_streamer,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi_streamer.InstanceName(), SwaggerInfoopenapi_streamer)
}
