// Package collector Code generated by swaggo/swag. DO NOT EDIT
package collector

import "github.com/swaggo/swag"

const docTemplateopenapi_collector = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns 200 while the collector process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns a JSON snapshot of collector counters: messages consumed, DB writes (success/error), validation errors, last write timestamp, and uptime.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Collector metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.Snapshot"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 when the DB is connected, migration has run, and the consumption loop is active. Returns 503 otherwise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.Snapshot": {
            "type": "object",
            "properties": {
                "db_writes_error_total": {
                    "type": "integer"
                },
                "db_writes_success_total": {
                    "type": "integer"
                },
                "last_db_write_timestamp_seconds": {
                    "type": "number"
                },
                "messages_consumed_total": {
                    "type": "integer"
                },
                "uptime_seconds": {
                    "type": "integer"
                },
                "validation_errors_total": {
                    "type": "integer"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.ReadyResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        }
    }
}`

// SwaggerInfoopenapi_collector holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi_collector = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GPU Telemetry Pipeline — Collector API",
	Description:      "Internal health and observability API for the Telemetry Collector service.",
	InfoInstanceName: "openapi_collector",
	SwaggerTemplate:  docTemplateopenapi_collector,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi_collector.InstanceName(), SwaggerInfoopenapi_collector)
}
