// Package message_queue Code generated by swaggo/swag. DO NOT EDIT
package message_queue

import "github.com/swaggo/swag"

const docTemplateopenapi_message_queue = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns 200 while the process is alive. Used by Kubernetes as a liveness probe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message_queue.HealthResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "description": "Enqueues a single GPU telemetry data point. Blocks until a slot is free or the publish timeout elapses.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Publish a telemetry message",
                "parameters": [
                    {
                        "description": "Telemetry message to enqueue",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message_queue.PublishRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message accepted; returns the assigned message_id",
                        "schema": {
                            "$ref": "#/definitions/message_queue.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid request body",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Queue is full; retry with backoff",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Queue is shutting down",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/ack": {
            "post": {
                "description": "Marks delivered messages as processed. Returns 207 Multi-Status if any delivery_id was rejected (expired lease, wrong consumer, or unknown ID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Acknowledge messages",
                "parameters": [
                    {
                        "description": "Consumer ID and list of delivery IDs to acknowledge",
                        "name": "ack",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message_queue.AckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All messages acknowledged",
                        "schema": {
                            "$ref": "#/definitions/message_queue.AckResult"
                        }
                    },
                    "207": {
                        "description": "Partial success; check rejected_ids",
                        "schema": {
                            "$ref": "#/definitions/message_queue.AckResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/consume": {
            "get": {
                "description": "Long-polls for up to ` + "`" + `long_poll_timeout` + "`" + ` seconds. Returns up to ` + "`" + `batch_size` + "`" + ` messages leased to ` + "`" + `consumer_id` + "`" + `. Returns 204 on timeout with no messages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Consume messages (long poll)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier for this consumer instance (typically pod hostname)",
                        "name": "consumer_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of messages to return (default: server-configured batch size)",
                        "name": "batch_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maximum wait duration, e.g. 30s (default: server-configured value)",
                        "name": "long_poll_timeout",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "One or more messages leased to the caller",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ConsumeResponse"
                        }
                    },
                    "204": {
                        "description": "Long-poll timed out; no messages available — poll again immediately"
                    },
                    "400": {
                        "description": "consumer_id missing",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Queue is shutting down",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns a JSON snapshot of queue counters (published, acked, redelivered, dropped) and live state (depth, capacity, in-flight).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Queue metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message_queue.Snapshot"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 when the queue is ready to serve traffic, including live queue depth and capacity. Returns 503 during shutdown.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/message_queue.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "message_queue.AckRequest": {
            "type": "object",
            "required": [
                "consumer_id",
                "delivery_ids"
            ],
            "properties": {
                "consumer_id": {
                    "type": "string"
                },
                "delivery_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "message_queue.AckResult": {
            "type": "object",
            "properties": {
                "acked": {
                    "type": "integer"
                },
                "rejected": {
                    "type": "integer"
                },
                "rejected_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "message_queue.ConsumeResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message_queue.DeliveryItem"
                    }
                }
            }
        },
        "message_queue.DeliveryItem": {
            "type": "object",
            "properties": {
                "delivery_id": {
                    "type": "string"
                },
                "lease_expires": {
                    "type": "string"
                },
                "message": {
                    "$ref": "#/definitions/model.TelemetryMessage"
                }
            }
        },
        "message_queue.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "message_queue.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "message_queue.PublishRequest": {
            "type": "object",
            "required": [
                "metric_name",
                "timestamp",
                "uuid",
                "value"
            ],
            "properties": {
                "device": {
                    "type": "string"
                },
                "gpu_id": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "labels_raw": {
                    "type": "string"
                },
                "metric_name": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "message_queue.PublishResponse": {
            "type": "object",
            "properties": {
                "message_id": {
                    "type": "string"
                }
            }
        },
        "message_queue.ReadyResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "queue_depth": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "message_queue.Snapshot": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "in_flight": {
                    "type": "integer"
                },
                "queue_depth": {
                    "type": "integer"
                },
                "total_acked": {
                    "type": "integer"
                },
                "total_dropped": {
                    "type": "integer"
                },
                "total_published": {
                    "type": "integer"
                },
                "total_redelivered": {
                    "type": "integer"
                },
                "uptime_seconds": {
                    "type": "integer"
                }
            }
        },
        "model.TelemetryMessage": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "gpu_id": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "labels_raw": {
                    "type": "string"
                },
                "message_id": {
                    "description": "MessageID is assigned by the message-queue service upon receipt.\nIt is stable across redeliveries.",
                    "type": "string"
                },
                "metric_name": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID uniquely identifies a GPU across all hosts.",
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoopenapi_message_queue holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi_message_queue = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GPU Telemetry Pipeline — Message Queue API",
	Description:      "Custom in-memory ring-buffer message queue. Streamers publish telemetry; Collectors consume and ack.",
	InfoInstanceName: "openapi_message_queue",
	SwaggerTemplate:  docTemplateopenapi_message_queue,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi_message_queue.InstanceName(), SwaggerInfoopenapi_message_queue)
}
